# Generated by Django 3.2.14 on 2022-08-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decoderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoder',
            name='dev_id2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoderapp.devicelist', verbose_name='Device ID'),
        ),
    ]
