# Generated by Django 3.2.14 on 2022-08-11 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decoderapp', '0003_alter_decoder_dev_id2'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelist',
            name='highlighted',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='devicelist',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='auth.user'),
            preserve_default=False,
        ),
    ]
