# Generated by Django 3.2.14 on 2022-08-11 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decoderapp', '0004_auto_20220811_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decodr', to=settings.AUTH_USER_MODEL),
        ),
    ]
