# Generated by Django 3.2.14 on 2022-08-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decoderapp', '0005_alter_devicelist_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicelist',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='devicelist',
            name='owner',
        ),
    ]
