# Generated by Django 3.2.14 on 2022-08-11 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decoderapp', '0006_auto_20220811_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelist',
            name='highlighted',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='devicelist',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='decodr', to='auth.user'),
            preserve_default=False,
        ),
    ]
