# Generated by Django 3.1 on 2022-07-30 03:56

from django.db import migrations, models
import django.db.models.deletion
import jsoneditor.fields.django3_jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.CharField(max_length=6, verbose_name='Device ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(default=0, verbose_name='Application ID')),
                ('schema_json', models.TextField(help_text='Please enter the decoding schema for IOT device in JSON format', max_length=200, verbose_name='Schhema')),
                ('start_date', models.DateTimeField(verbose_name='Start')),
                ('end_date', models.DateTimeField(verbose_name='End')),
            ],
        ),
        migrations.CreateModel(
            name='Schema2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_json2', models.TextField(help_text='Please enter the decoding schema for IOT device in JSON format', max_length=200, verbose_name='Schhema 2')),
                ('schema_jsonfield', jsoneditor.fields.django3_jsonfield.JSONField(default=list)),
                ('app_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotapp.devicelist')),
            ],
        ),
    ]
